### ISSUE TITLE
Give more details on how to use this with Spark Application

### ISSUE THREAD

**Issue by anujchoudhury** [uber-common/jvm-profiler#15]
Could more details be given on how to use the Profiler (with different Consoles) for a spark application ?
I could find the details in the Readme for a normal Java Application, but the details on how to use it with a spark application could not be found.

**Comment by petro-rudenko** [comment]
Just add:
`spark.executor.extraJavaOptions -Djava.library.path=/jvm-profiler/target/jvm-profiler-0.0.7.jar=reporter=com.uber.profiling.reporters.ConsoleOutputReporter,tag=mytag,metricInterval=5000,sampleInterval=100`

You'll see results in stdout of yarn logs. But would be great to aggregate metrics and visualize them in some way, e.g like in : https://github.com/criteo/babar

**Comment by boy-uber** [comment]
Thanks Peter for replying! I will close this issue, and update README with link to https://eng.uber.com/jvm-profiler/ as well.

Also it is great that you mentioned visualization and the example for babar, we haven't got time to work on that yet.
