### ISSUE TITLE
Is it possible to integrate it with Spring MVC + Tomcat app

### ISSUE THREAD

**Issue by beginner** [uber-common/jvm-profiler#18]
Is it possible to integrate it with Spring MVC + Tomcat app

**Comment by felixcheung** [comment]
Quite possible? I don't think that has been attempted, yet.

**Comment by beginner** [comment]
Same run time VM args worked for me, without specifying any main class. Now I can see data published to Kafka topic. Any recommendation on how to make sense out of the data published to kafka?

**Comment by felixcheung** [comment]
did you check out the guide https://eng.uber.com/jvm-profiler/ ?

**Comment by boy-uber** [comment]
@beginner there are several ways you could query data in Kafka:

1. KSQL: https://www.confluent.io/blog/ksql-open-source-streaming-sql-for-apache-kafka/

2. Write a streaming job using Spark Stream or Flink, read the Kafka topics and save to Hadoop or database.

We use the second approach internally. If you want, you could also write a customer reporter in the jvm-profiler and write metrics to your database.

**Comment by misasagi1988** [comment]
same question: Is it possible to integrate it with Spring Boot application?

**Comment by boy-uber** [comment]
Hi misasagi1988, yes, it is possible. You could add "-javaagent:jvm-profiler-0.0.9.jar" argument to the java command which starts your Sparing Boot application.
