### ISSUE TITLE
StatsdOutputReporter

### ISSUE THREAD

**Issue by cozos** [uber-common/jvm-profiler#38]
Any reason why there is no StatsdOutputReporter? I'd be interested in writing one as I use Statsd to  collect metrics.

**Comment by felixcheung** [comment]
Great! Please consider contributing!

**Comment by cozos** [comment]
https://github.com/uber-common/jvm-profiler/pull/40/files

First pass at this, LMK what you think

**Comment by boy-uber** [comment]
Merged the code.

**Comment by felixcheung** [comment]
adding tests is a good idea still though ;)

**Comment by cozos** [comment]
I'll do that when I have some time.
