### ISSUE TITLE
Run JVM Profiler on a regular Filesystem

### ISSUE THREAD

**Issue by ramshankar1990** [uber-common/jvm-profiler#41]
I am trying to use the JVM profiler on a supercomputing cluster. To run the tool it requires the HDFS URL but the admins who are helping me with setting up the tool on the cluster would like to know if this tool can be run on a regular filesystem since using the HDFS URL could open up security issues from their end. I appreciate your help in this regard.

**Comment by boy-uber** [comment]
Hi Ram, yes, you could use it on a regular file system, with following steps:

1. Copy jvm-profiler-1.0.0.jar file to each machine in your cluster.
2. Add following argument to your java command: -javaagent:path/to/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.ConsoleOutputReporter

**Comment by ramshankar1990** [comment]
Thank you for the quick response. I will update the admins about this.
