### ISSUE TITLE
Cross Node Communication

### ISSUE THREAD

**Issue by rawlani** [uber-common/jvm-profiler#44]
Hi, I have been using Uber JVM profiler for profiling my Spark applications.
May I know if the profiler provides information on cross node communication?

**Comment by boy-uber** [comment]
Hi, glad you are using Uber JVM profiler! What do you mean "cross node communication"?

**Comment by rawlani** [comment]
Hi, apologies for the delay.
By Cross-node communication, I mean the Information on the data that is written and read between the multiple worker nodes and between the driver nodes and worker nodes.

**Comment by boy-uber** [comment]
I see. Thanks for explaining. It does not support such information then.

**Comment by rawlani** [comment]
Okay. Thanks for letting us know. Moreover, I also wanted to know if we can pull up any information about I/O stuff on each node?

**Comment by boy-uber** [comment]
There is some I/O stuff you could get, but not comprehensive IO metrics. You could add "ioProfiling=true" in the java agent parameters. And you could find what IO metrics it collect from this source file: https://github.com/uber-common/jvm-profiler/blob/master/src/main/java/com/uber/profiling/profilers/IOProfiler.java

**Comment by boy-uber** [comment]
Close inactive issue.
