### ISSUE TITLE
Profiling Spark Streaming application

### ISSUE THREAD

**Issue by ajames-branch** [uber-common/jvm-profiler#46]
I would like to know how the 'durationProfiling' will work in case of Spark streaming application.

**Comment by boy-uber** [comment]
durationProfiling will profile a given java method and capture how many times it runs and how long it runs. It doesn't matter if it is Spark streaming application.

**Comment by ajames-branch** [comment]
> durationProfiling will profile a given java method and capture how many times it runs and how long it runs. It doesn't matter if it is Spark streaming application.

Thank You @boy-uber
