### ISSUE TITLE
How to get method metrics? 

### ISSUE THREAD

**Issue by ajames-branch** [uber-common/jvm-profiler#47]
I would like to get details about number of times a method is invoked, duration for the method execution. I believe I should use 'durationPolling' feature. I am using following command:

-javaagent:jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.FileOutputReporter,outputDir=/tmp/ProfilerOut,ioProfiling=true,sampleInterval=2000,durationProfiling=io.jaal.spark.ingest.Publisher.getProducer

However I am seeing 'ProcessInfo.json' (along with 'CpuAndMemory.json', 'IO.json' and 'Stacktrace.json') and it does not seem to have the above metrics. Am I doing it correctly? Could anyone please help me here?

**Comment by boy-uber** [comment]
Hi, it looks correct "durationProfiling=io.jaal.spark.ingest.Publisher.getProducer". Would you verify that method is called in your application?

**Comment by ajames-branch** [comment]
> Hi, it looks correct "durationProfiling=io.jaal.spark.ingest.Publisher.getProducer". Would you verify that method is called in your application?

@boy-uber  Yes it is invoked multiple times. I will double verify that. Is there any cases where this will not work?

My function looks like this:
getProducer(brokerDetails).get().send(_lambda function_);

**Comment by boy-uber** [comment]
It should work with static function. The test case [here](https://github.com/uber-common/jvm-profiler/blob/master/src/test/java/com/uber/profiling/AgentITCase.java)  includes durationProfiling on static method.

**Comment by boy-uber** [comment]
Close inactive issue.
