### ISSUE TITLE
Using fileappender as output option

### ISSUE THREAD

**Issue by ajames-branch** [uber-common/jvm-profiler#49]
While profiling a spark application, if we are using the following setting:
`reporter=com.uber.profiling.reporters.FileOutputReporter,outputDir=/tmp/ProfilerOut`, is the output present in all the executor nodes or will it get aggregated and driver writes on its local directory?

**Comment by ajames-branch** [comment]
Also, do we have any metrics on the latency difference when we execute the application with and without profiling? Trying to understand if adding the profiler will add lag to the application execution.

**Comment by felixcheung** [comment]
I think `FileOutputReporter` will be written to local directories. 
about latency or overhead, @boy-uber should have the number to share, but it should be very low.

**Comment by ajames-branch** [comment]
Thank you @felixcheung
