### ISSUE TITLE
Adding ThreadMXBean information in the profiler

### ISSUE THREAD

**Issue by psuri** [uber-common/jvm-profiler#52]
ThreadMXBean from the ManagementFactory is capable of providing Thread level metrics in the profiler which could be very useful while trying to debug memory issues as well. Few functions which I have found useful:

threadMXBean.getThreadCount();
threadMXBean.getPeakThreadCount()
threadMXBean.getTotalStartedThreadCount()

I could add these as a PR perhaps in an existing Profiler class or create a new Thread level profiler class.

**Comment by boy-uber** [comment]
Yes, this is a good suggestion! Please feel free to add a PR. Also thanks for contributing!

**Comment by rahul26goyal** [comment]
Is anyone working on this request? If not, I am willing to contribute to this if someone can guide me a bit. 
I have gottne a basic understanding of the overall flow. cc :  @boy-uber

**Comment by boy-uber** [comment]
Hi Rahul, I haven't got update that someone is working on this. It will be very welcome if you add code to support this :) Thanks!

**Comment by boy-uber** [comment]
PR merged
