### ISSUE TITLE
Documentation for metrics collected

### ISSUE THREAD

**Issue by m-vemuri** [uber-common/jvm-profiler#72]
#### Summary:

This ticket is a suggestion for improving the documentation by adding a description of the metrics collected by the profiler.
<br>

#### Details:

As noted in https://github.com/uber-common/jvm-profiler/issues/50, there is currently no documentation describing the metrics that are collected.
Adding a description of what each collected metric represents to the documentation might add value by:
1. Creating a quick reference for developers.
2. Increasing the usability of the repository/profiler.

The recommendation is to add something along the lines of the sample below.

|  Name                                                  |  Description                                                    |  Sample Value                                |  Note                                                                     |
|--------------------------------------------------------|-----------------------------------------------------------------|----------------------------------------------|---------------------------------------------------------------------------------------|
|bufferPools-direct-totalCapacity                        |Available capacity in bytes in the direct buffer pool.           |18949                                         |Capacity should be similar to memoryUsed for a healthy JVM.                            |
|gc-PSMarkSweep-collectionCount                          |Total number of collections that have occurred for PS MarkSweep. |7                                             |-1 if collection count is undefined for this collector.                                |
<br>

#### Relevant Branch:

I have started some work on this, which can be found [here](https://github.com/m-vemuri/jvm-profiler/blob/feat/readme_for_measurement_descriptions/metricDetails.md). The information provided in the mark-down is based on the source code of the profiler, the `java.lang` documentation of the APIs that are used by the profiler and personal knowledge.

The documentation linked above is incomplete since I wanted to ensure that this change is acceptable before spending more time on it.

**Comment by jodom961** [comment]
thanks for throwing this together... the branch really helped me! Hope it gets further looks from the uber team so people don't have to search git issues for it 👍

**Comment by boy-uber** [comment]
Great, thanks @m-vemuri for writing the doc! Would you like to submit a pull request to this repo so I could merge it?

**Comment by m-vemuri** [comment]
Thanks @jodom961. Glad it was useful and helpful.

@boy-uber sure thing. I'll submit a pull request once its completed.

**Comment by boy-uber** [comment]
Sounds good, thanks :)

**Comment by m-vemuri** [comment]
@boy-uber I have created PR https://github.com/uber-common/jvm-profiler/pull/79.

**Comment by boy-uber** [comment]
Merged PR.
