### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of com.fasterxml.jackson.core:jackson-core:jar

### ISSUE THREAD

**Issue by Bing-ok** [uber-common/jvm-profiler#76]
Hi, there are multiple versions of <b><i>com.fasterxml.jackson.core:jackson-core</i></b> in <b><i>jvm-profiler-master</i></b>. As shown in the following dependency tree, according to Maven's “nearest wins” strategy, only <b><i>com.fasterxml.jackson.core:jackson-core:2.8.11</i></b> can be loaded, <b><i>com.fasterxml.jackson.core:jackson-core:2.10.0.pr1</i></b> will be shadowed.

As <b><i>com.fasterxml.jackson.core:jackson-core:2.10.0.pr1</i></b> has not been loaded during the building process, several methods are missing. However, the missing methods:
<b><i>1. org.apache.maven.artifact.versioning.ManagedVersionMap: void init (java.util.Map)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.uber.profiling.util.JsonUtils: java.lang.String serialize(java.lang.Object)&gt; jvm-profiler-master\target\classes
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.String writeValueAsString(java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializeValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void _serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.StdScalarSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase: com.fasterxml.jackson.core.type.WritableTypeId writeTypeSuffix(com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.core.type.WritableTypeId)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypeSuffix(com.fasterxml.jackson.core.type.WritableTypeId)&gt; 
</details>

<b><i>2. com.fasterxml.jackson.core.type.WritableTypeId: void init (java.lang.Object,com.fasterxml.jackson.core.JsonToken)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.uber.profiling.util.JsonUtils: java.lang.String serialize(java.lang.Object)&gt; jvm-profiler-master\target\classes
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.String writeValueAsString(java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializeValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void _serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.StdScalarSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.jsontype.TypeSerializer: com.fasterxml.jackson.core.type.WritableTypeId typeId(java.lang.Object,com.fasterxml.jackson.core.JsonToken)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.core.type.WritableTypeId: void init (java.lang.Object,com.fasterxml.jackson.core.JsonToken)&gt; 
</details>

<b><i>3. com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.type.WritableTypeId)</i></b>
<details>
<summary>Check for details of invocation</summary>
</br>paths------
</br>&lt;com.uber.profiling.util.JsonUtils: java.lang.String serialize(java.lang.Object)&gt; jvm-profiler-master\target\classes
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: java.lang.String writeValueAsString(java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ObjectMapper: void _configAndWriteValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void serializeValue(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.DefaultSerializerProvider: void _serialize(com.fasterxml.jackson.core.JsonGenerator,java.lang.Object,com.fasterxml.jackson.databind.JsonSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.ReferenceTypeSerializer: void serialize(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.ser.std.StdScalarSerializer: void serializeWithType(java.lang.Object,com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.databind.SerializerProvider,com.fasterxml.jackson.databind.jsontype.TypeSerializer)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.databind.jsontype.impl.TypeSerializerBase: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.JsonGenerator,com.fasterxml.jackson.core.type.WritableTypeId)&gt; Repositories\com\fasterxml\jackson\core\jackson-databind\2.10.0.pr1\jackson-databind-2.10.0.pr1.jar
</br>&lt;com.fasterxml.jackson.core.JsonGenerator: com.fasterxml.jackson.core.type.WritableTypeId writeTypePrefix(com.fasterxml.jackson.core.type.WritableTypeId)&gt; 
</details>

The above missing methods are actually referenced by <b><i>jvm-profiler-master</i></b>, which will cause “NoSuchMethodErrors” at runtime.

Suggested fixing solutions:
1. Upgrade direct dependency <b><i>com.fasterxml.jackson.core:jackson-core</i></b> from <b><i>2.8.11</i></b> to <b><i>2.10.0.pr1 </i></b>.

Thank you very much for your attention.
Best regards,

Dependency tree----

<details>
<summary>click for details</summary>
</br>[INFO] com.uber:jvm-profiler:jar:1.0.0
</br>[INFO] +- org.apache.kafka:kafka-clients:jar:0.11.0.2:compile
</br>[INFO] |  +- net.jpountz.lz4:lz4:jar:1.3.0:compile
</br>[INFO] |  +- org.xerial.snappy:snappy-java:jar:1.1.2.6:compile
</br>[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.25:compile
</br>[INFO] +- org.apache.commons:commons-lang3:jar:3.5:compile
</br>[INFO] +- <b>com.fasterxml.jackson.core:jackson-core:jar:2.8.11:compile</b>
</br>[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.10.0.pr1:compile
</br>[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.0.pr1:compile
</br>[INFO] |  \- <b>(com.fasterxml.jackson.core:jackson-core:jar:2.10.0.pr1:compile - omitted for conflict with 2.8.11)</b>
</br>[INFO] +- org.javassist:javassist:jar:3.21.0-GA:compile
</br>[INFO] +- org.yaml:snakeyaml:jar:1.18:compile
</br>[INFO] +- org.apache.httpcomponents:httpclient:jar:4.3.6:compile
</br>[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.3.3:compile
</br>[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
</br>[INFO] |  \- commons-codec:commons-codec:jar:1.6:compile
</br>[INFO] \- junit:junit:jar:4.8.1:test
</details>

**Comment by Bing-ok** [comment]
Could you help me review this issue? 👍 Thanks! @boy-uber

**Comment by boy-uber** [comment]
yes, thanks for the details for the issue, I updated jackson-databind to 2.8.11 in pom.xml just now.

**Comment by Bing-ok** [comment]
Thanks for your support!
