### ISSUE TITLE
RollingFileOutputReporter support

### ISSUE THREAD

**Issue by V1ncentzzZ** [uber-common/jvm-profiler#87]
Hi, I hava an idea like the titile. Because the file is not allowed to keep growing in streaming jobs. So we hava to use rolling file for it. What do you think?

**Comment by V1ncentzzZ** [comment]
Can i contribute to this? @hiboyang

**Comment by hiboyang** [comment]
Yes, your contribution will be great! Thanks!

**Comment by vectorijk** [comment]
close the issue as PR #88  is merged. feel free to reopen if needed
