### ISSUE TITLE
Does this work with pyspark applications?

### ISSUE THREAD

**Issue by unitedCoder** [uber-common/jvm-profiler#90]
I have tried using the profiler, following the instructions in the README file, but I don't see any output or logs. May be I am missing something.
I am running a pyspark application, using jupyter. (spark version:2.3.2)

.config("spark.jars","/tmp/profileJar/jvm-profiler-1.0.0.jar")

.config("spark.driver.extraJavaOptions","-javaagent:/tmp/profileJar/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.FileOutputReporter,metricInterval=5000,sampleInterval=5000,ioProfiling=true,outputDir=/tmp/ProfilerOut")

.config("spark.executor.extraJavaOptions","-javaagent:/tmp/profileJar/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.FileOutputReporter,metricInterval=5000,sampleInterval=5000,ioProfiling=true,outputDir=/tmp/ProfilerOut")

Please let me know if you have any inputs/suggestions.

**Comment by arverma** [comment]
I am also in the same situation, can't see any profiler logs. How did you resolve it?
